package tests;// Generated by Selenium IDE

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import pages.MainPage;

class AuthTest extends BaseTest {

    @Test
    void test() {
        MainPage mainPage = new MainPage(driver);
        mainPage.open();

        driver.findElement(By.id("login-link")).click();
        WebElement element = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.id("email"))
        );
        element.click();
        element.sendKeys("bobi-boba");
        element.sendKeys(Keys.ENTER);

        element = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.id("email-error"))
        );
        Assertions.assertTrue(element.isDisplayed());
    }
}
