// Generated by Selenium IDE
package tests;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import pages.MainPage;

import java.time.Duration;

public class SearchTest extends BaseTest {

    @Test
    public void searchForJava() {
        MainPage mainPage = new MainPage(driver);
        mainPage.open();

        driver.findElement(By.id("keyword-bar-in-search")).click();
        driver.findElement(By.id("keyword-bar-in-search")).sendKeys("Java");
        driver.findElement(By.id("location-search-submit")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
        WebElement header = wait.until(
                ExpectedConditions.visibilityOfElementLocated(By.xpath("//main[@id='main']/div/div/div/div[2]/div/h1"))
        );

        String headerText = header.getText();
        assertTrue(headerText.contains("Java"),
                "Заголовок не содержит слово 'Java': " + headerText);
    }
}
